DROP TABLE IF EXISTS tracks;


CREATE TABLE tracks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  artist TEXT NOT NULL,
  genre TEXT NOT NULL,
  length_ INTEGER NOT NULL
);

